routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'SiteController@actionIndex')->name('/');

Auth::routes(['register' => false]);

Route::get('/admin', 'SiteController@actionAdmin')->name('admin');

Route::resource('users', 'UserController');

Route::resource('modules', 'ModuleController');

Route::resource('teachers', 'TeacherController');

Route::resource('deadlines', 'DeadlineController');
Route::get('/deadlines/{deadline}/complete', 'DeadlineController@actionComplete')->name('deadlines.complete');

Route::resource('tags', 'TagController');

app/Module.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Module
 * @package App
 * @property int id
 * @property int teacher_id
 * @property int coordinator_id
 * @property string name
 * @property string description
 * @property int period
 * @property int ec
 * @property boolean completed
 * @property int score
 * @property string type
 * @property string deadline
 * @property string file_path
 * @property string created_at
 * @property string updated_at
 *
 * @property Teacher teacher
 * @property Teacher coordinator
 * @property Deadline[] deadlines
 */
class Module extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'period',
        'ec',
        'completed',
        'score',
        'type',
        'teacher_id',
        'coordinator_id',
        'file_path',
    ];

    public static function getModuleIds()
    {
        return [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16];
    }

    public static function getSemesterIds()
    {
        return [1, 2, 3, 4, 5, 6, 7, 8];
    }

    protected $casts = [
        'completed' => 'boolean',
    ];

    public function teacher()
    {
        return $this->belongsTo(Teacher::class, 'teacher_id', 'id');
    }

    public function coordinator()
    {
        return $this->belongsTo(Teacher::class, 'coordinator_id', 'id');
    }

    public function deadlines(){
        return $this->hasMany(Deadline::class);
    }
}

app/Http/Controllers/ModuleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ModuleStoreUpdateRequest;
use App\Module;
use App\Teacher;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class ModuleController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return void
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', Module::class);
        return view('module.create')->with([
            'types' => ['assessment', 'tentamen'],
            'teachers' => Teacher::all(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ModuleStoreUpdateRequest $request
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function store(ModuleStoreUpdateRequest $request)
    {
        $this->authorize('create', Module::class);
        $data = $request->validated();
        if ($request->file_path) {
            $file_path = $request->file_path->store('files', 'public');
            $fileData = ['file_path' => $file_path];
            $data = array_merge($data, $fileData);
        }
        Module::create($data);
        return redirect()->route('admin');
    }

    /**
     * Display the specified resource.
     *
     * @param Module $module
     * @return void
     */
    public function show(Module $module)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Module $module
     * @return Factory|View
     * @throws AuthorizationException
     */
    public function edit(Module $module)
    {
        $this->authorize('update', $module);
        return view('module.edit')->with([
            'module' => $module,
            'types' => ['assessment', 'tentamen'],
            'teachers' => Teacher::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ModuleStoreUpdateRequest $request
     * @param Module $module
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(ModuleStoreUpdateRequest $request, Module $module)
    {
        $this->authorize('update', $module);
        $data = $request->validated();
        if ($request->file_path) {
            $file_path = $request->file_path->store('files', 'public');
            $fileData = ['file_path' => $file_path];
            $data = array_merge($data, $fileData);
        }
        $module->update($data);
        return redirect()->route('admin');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Module $module
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Module $module)
    {
        $this->authorize('delete', $module);
        Module::destroy($module->id);
        return redirect()->back();
    }
}

resources/views/module/create.blade.php
@extends('layouts.default')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <form action="{{ route('modules.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('POST')

                    <div class="row mb-2">
                        <div class="col-md-12">
                            <h2 class="text-primary">Module aanmaken</h2>
                            <p>Maak een module aan om voortang voor deze module bij te houden.</p>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="name" class="text-secondary">Module naam</label>
                            <input id="name" type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name" value="{{ old('name') }}"
                                   placeholder="Vul hier de naam van de module in">
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="description" class="text-secondary">Omschrijving</label>
                            <input id="description" type="text"
                                   class="form-control @error('description') is-invalid @enderror"
                                   name="description" value="{{ old('description') }}" autocomplete="description"
                                   placeholder="Vul hier de omschrijving van de module in">
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="period" class="text-secondary">Blok</label>
                            <input id="period" type="text"
                                   class="form-control @error('period') is-invalid @enderror"
                                   name="period" value="{{ old('period') }}" autocomplete="period"
                                   placeholder="Vul hier de period van de module in">
                            @error('period')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="ec" class="text-secondary">EC</label>
                            <input id="ec" type="text"
                                   class="form-control @error('ec') is-invalid @enderror"
                                   name="ec" value="{{ old('ec') }}" autocomplete="ec"
                                   placeholder="Vul hier de ec van de module in">
                            @error('ec')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="completed" class="text-secondary">Completed <small>(niet verplicht)</small></label>
                            <input id="completed" type="text"
                                   class="form-control @error('completed') is-invalid @enderror"
                                   name="completed" value="{{ old('completed') }}"
                                   autocomplete="completed"
                                   placeholder="Vul hier de status van de module in (0 of 1)">
                            @error('completed')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="score" class="text-secondary">Score <small>(niet verplicht)</small></label>
                            <input id="score" type="text"
                                   class="form-control @error('score') is-invalid @enderror"
                                   name="score" value="{{ old('score') }}" autocomplete="score"
                                   placeholder="Vul hier de score van de module in">
                            @error('score')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="type">Type</label>
                            <select id="type" name="type"
                                    class="custom-select @error('type') is-invalid @enderror">
                                @if(old('type') == null)
                                    <option value="" disabled selected hidden>Kies een type voor de module</option>
                                @endif
                                @foreach($types as $type)
                                    @if (old('type') == $type)
                                        <option value="{{ $type }}" selected>{{ $type }}</option>
                                    @else
                                        <option value="{{ $type }}">{{ $type }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('type')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="file_path" class="text-secondary">ZIP-bestand <small>(niet verplicht)</small></label>
                            <input type="file" class="form-control-file" id="file_path"
                                   name="file_path">
                            @error('file_path')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="type">Teacher</label>
                            <select id="teacher_id" name="teacher_id"
                                    class="custom-select @error('teacher_id') is-invalid @enderror">
                                @if(old('teacher_id') == null)
                                    <option value="" disabled selected hidden>Kies een teacher voor de module</option>
                                @endif
                                @foreach($teachers as $teacher)
                                    @if (old('teacher_id') == $teacher->id)
                                        <option value="{{ $teacher->id }}" selected>{{ $teacher->name }}</option>
                                    @else
                                        <option value="{{ $teacher->id }}">{{ $teacher->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('teacher_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="type">Coordinator</label>
                            <select id="coordinator_id" name="coordinator_id"
                                    class="custom-select @error('coordinator_id') is-invalid @enderror">
                                @if(old('coordinator_id') == null)
                                    <option value="" disabled selected hidden>Kies een coordinator voor de module</option>
                                @endif
                                @foreach($teachers as $teacher)
                                    @if (old('coordinator_id') == $teacher->id)
                                        <option value="{{ $teacher->id }}" selected>{{ $teacher->name }}</option>
                                    @else
                                        <option value="{{ $teacher->id }}">{{ $teacher->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('coordinator_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-12 d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary">Aanmaken van module</button>
                            <a href="{{ route('admin') }}" class="text-secondary align-self-end">Annuleren</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/module/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <form action="{{ route('modules.update', $module->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')

                    <div class="row mb-2">
                        <div class="col-md-12">
                            <h2 class="text-primary">Module bewerken</h2>
                            <p>Bewerk een module aan om voortang voor deze module bij te houden.</p>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="name" class="text-secondary">Module naam</label>
                            <input id="name" type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name" value="{{ old('name') ?? $module->name }}"
                                   placeholder="Vul hier de naam van de module in">
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="description" class="text-secondary">Omschrijving</label>
                            <input id="description" type="text"
                                   class="form-control @error('description') is-invalid @enderror"
                                   name="description" value="{{ old('description') ?? $module->description }}"
                                   autocomplete="description"
                                   placeholder="Vul hier de omschrijving van de module in">
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="period" class="text-secondary">Blok</label>
                            <input id="period" type="text"
                                   class="form-control @error('period') is-invalid @enderror"
                                   name="period" value="{{ old('period') ?? $module->period }}" autocomplete="period"
                                   placeholder="Vul hier de period van de module in">
                            @error('period')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="ec" class="text-secondary">EC</label>
                            <input id="ec" type="text"
                                   class="form-control @error('ec') is-invalid @enderror"
                                   name="ec" value="{{ old('ec') ?? $module->ec }}" autocomplete="ec"
                                   placeholder="Vul hier de ec van de module in">
                            @error('ec')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="completed" class="text-secondary">Completed <small>(niet
                                    verplicht)</small></label>
                            <input id="completed" type="text"
                                   class="form-control @error('completed') is-invalid @enderror"
                                   name="completed" value="{{ old('completed') ?? $module->completed ? 1 : 0 }}"
                                   autocomplete="completed"
                                   placeholder="Vul hier de status van de module in (0 of 1)">
                            @error('completed')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="score" class="text-secondary">Score <small>(niet verplicht)</small></label>
                            <input id="score" type="text"
                                   class="form-control @error('score') is-invalid @enderror"
                                   name="score" value="{{ old('score') ?? $module->score ?? '' }}" autocomplete="score"
                                   placeholder="Vul hier de score van de module in">
                            @error('score')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="type">Type</label>
                            <select id="type" name="type"
                                    class="custom-select @error('type') is-invalid @enderror">
                                @foreach($types as $type)
                                    @if (old('type') ?? $module->type == $type)
                                        <option value="{{ $type }}" selected>{{ $type }}</option>
                                    @else
                                        <option value="{{ $type }}">{{ $type }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('type')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="file_path" class="text-secondary">ZIP-bestand <small>(niet verplicht)</small></label>
                            <input type="file" class="form-control-file" id="file_path"
                                   name="file_path">
                            @error('file_path')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="type">Teacher</label>
                            <select id="teacher_id" name="teacher_id"
                                    class="custom-select @error('teacher_id') is-invalid @enderror">
                                @if(old('teacher_id') ?? $module->teacher_id == null)
                                    <option value="" disabled selected hidden>Kies een coordinator voor de module
                                    </option>
                                @endif
                                @foreach($teachers as $teacher)
                                    @if (old('teacher_id') ?? $module->teacher->id ?? '' == $teacher->id)
                                        <option value="{{ $teacher->id }}" selected>{{ $teacher->name }}</option>
                                    @else
                                        <option value="{{ $teacher->id }}">{{ $teacher->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('teacher_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="type">Coordinator</label>
                            <select id="coordinator_id" name="coordinator_id"
                                    class="custom-select @error('coordinator_id') is-invalid @enderror">
                                @if(old('coordinator_id') ?? $module->coordinator_id == null)
                                    <option value="" disabled selected hidden>Kies een coordinator voor de module
                                    </option>
                                @endif
                                @foreach($teachers as $teacher)
                                    @if (old('coordinator_id') ?? $module->coordinator->id ?? '' == $teacher->id)
                                        <option value="{{ $teacher->id }}" selected>{{ $teacher->name }}</option>
                                    @else
                                        <option value="{{ $teacher->id }}">{{ $teacher->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('coordinator_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-12 d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary">Bewerken van module</button>
                            <a href="{{ route('admin') }}" class="text-secondary align-self-end">Annuleren</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection