routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'SiteController@actionIndex')->name('/');

Auth::routes(['register' => false]);

Route::get('/admin', 'SiteController@actionAdmin')->name('admin');

Route::resource('users', 'UserController');

Route::resource('modules', 'ModuleController');

Route::resource('teachers', 'TeacherController');

Route::resource('deadlines', 'DeadlineController');
Route::get('/deadlines/{deadline}/complete', 'DeadlineController@actionComplete')->name('deadlines.complete');

Route::resource('tags', 'TagController');

app/Deadline.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Deadline
 * @package App
 * @property int id
 * @property int module_id
 * @property string name
 * @property string deadline_at
 * @property boolean completed
 * @property int difficulty_id
 * @property int time_commitment_id
 * @property int fun_id
 * @property string created_at
 * @property string updated_at
 *
 * @property Module module
 * @property Tag difficulty
 * @property Tag time_commitment
 * @property Tag fun
 */
class Deadline extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'module_id',
        'name',
        'deadline_at',
        'difficulty_id',
        'time_commitment_id',
        'fun_id',
    ];

    protected $casts = [
        'completed' => 'boolean',
    ];

    public function module()
    {
        return $this->belongsTo(Module::class);
    }

    public function difficulty()
    {
        return $this->belongsTo(Tag::class, 'difficulty_id', 'id');
    }

    public function time_commitment()
    {
        return $this->belongsTo(Tag::class, 'time_commitment_id', 'id');
    }

    public function fun()
    {
        return $this->belongsTo(Tag::class, 'fun_id', 'id');
    }
}

app/Http/Controllers/DeadlineController.php
<?php

namespace App\Http\Controllers;

use App\Deadline;
use App\Http\Requests\DeadlineStoreUpdateRequest;
use App\Module;
use App\Tag;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class DeadlineController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Factory|View
     * @throws AuthorizationException
     */
    public function index(Request $request)
    {
        $this->authorize('viewAny', Deadline::class);
        $search = $request->search ?? '';

        $deadlineSort = $request->deadlineSort ?? 'none';
        $deadlineTimeSort = $request->deadlineTimeSort ?? 'none';
        $moduleSort = $request->moduleSort ?? 'none';
        $docentSort = $request->docentSort ?? 'none';
        $difficultySort = $request->difficultySort ?? 'none';
        $timeCommitmentSort = $request->timeCommitmentSort ?? 'none';
        $funSort = $request->funSort ?? 'none';

        $query = Deadline::query()->where('deadlines.name', 'like', '%'.$search.'%');

        if ($deadlineSort == 'asc' || $deadlineSort == 'desc') {
            $query->orderBy('deadlines.name', $deadlineSort);
        }
        if ($deadlineTimeSort == 'asc' || $deadlineTimeSort == 'desc') {
            $query->orderBy('deadlines.deadline_at', $deadlineTimeSort);
        }
        if ($moduleSort == 'asc' || $moduleSort == 'desc') {
            $query->rightJoin('modules', 'deadlines.module_id', '=', 'modules.id');
            $query->orderBy('modules.name', $moduleSort);
        }
        if ($docentSort == 'asc' || $docentSort == 'desc') {
            $query->rightJoin('modules', 'deadlines.module_id', '=', 'modules.id');
            $query->orderBy('modules.teacher_id', $docentSort);
        }
        if ($difficultySort == 'asc' || $difficultySort == 'desc') {
            $query->orderBy('difficulty_id', $difficultySort);
        }
        if ($timeCommitmentSort == 'asc' || $timeCommitmentSort == 'desc') {
            $query->orderBy('time_commitment_id', $timeCommitmentSort);
        }
        if ($funSort == 'asc' || $funSort == 'desc') {
            $query->orderBy('fun_id', $funSort);
        }

        $data = $query->orderBy('deadlines.updated_at', 'desc')->paginate();
        return view('deadline.index')->with([
            'data' => $data->items(),
            'search' => $search,
            'deadlineSort' => $deadlineSort,
            'deadlineTimeSort' => $deadlineTimeSort,
            'moduleSort' => $moduleSort,
            'docentSort' => $docentSort,
            'difficultySort' => $difficultySort,
            'timeCommitmentSort' => $timeCommitmentSort,
            'funSort' => $funSort,
            'tags' => Tag::all(),
            'totalCount' => $data->total(),
            'currentPage' => $data->currentPage(),
            'lastPage' => $data->lastPage(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', Deadline::class);
        return view('deadline.create')->with([
            'modules' => Module::all(),
            'difficulty_tags' => Tag::where('type', '=', 'difficulty')->get(),
            'time_commitment_tags' => Tag::where('type', '=', 'time_commitment')->get(),
            'fun_tags' => Tag::where('type', '=', 'fun')->get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param DeadlineStoreUpdateRequest $request
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function store(DeadlineStoreUpdateRequest $request)
    {
        $this->authorize('create', Deadline::class);
        $data = $request->validated();
        Deadline::create($data);
        return redirect()->route('deadlines.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Deadline $deadline
     * @return void
     */
    public function show(Deadline $deadline)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Deadline $deadline
     * @return Factory|View
     * @throws AuthorizationException
     */
    public function edit(Deadline $deadline)
    {
        $this->authorize('update', $deadline);
        return view('deadline.edit')->with([
            'deadline' => $deadline,
            'modules' => Module::all(),
            'difficulty_tags' => Tag::where('type', '=', 'difficulty')->get(),
            'time_commitment_tags' => Tag::where('type', '=', 'time_commitment')->get(),
            'fun_tags' => Tag::where('type', '=', 'fun')->get(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param DeadlineStoreUpdateRequest $request
     * @param Deadline $deadline
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(DeadlineStoreUpdateRequest $request, Deadline $deadline)
    {
        $this->authorize('update', $deadline);
        $data = $request->validated();
        $deadline->update($data);
        return redirect()->route('deadlines.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Deadline $deadline
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Deadline $deadline)
    {
        $this->authorize('delete', $deadline);
        Deadline::destroy($deadline->id);
        return redirect()->back();
    }

    /**
     * @param Deadline $deadline
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function actionComplete(Deadline $deadline)
    {
        $this->authorize('update', $deadline);
        if ($deadline->completed) $deadline->completed = false;
        else $deadline->completed = true;
        $deadline->save();
        return redirect()->back();
    }
}

resources/views/deadline/create.blade.php
@extends('layouts.default')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <form action="{{ route('deadlines.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('POST')

                    <div class="row mb-2">
                        <div class="col-md-12">
                            <h2 class="text-primary">Deadline aanmaken</h2>
                            <p>Maak een deadline aan om belangrijke momenten in een module bij te houden.</p>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="name" class="text-secondary">Naam / Omschrijving</label>
                            <input id="name" type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name" value="{{ old('name') }}"
                                   placeholder="Vul hier de naam/omschrijving van de deadine in">
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="deadline_at" class="text-secondary">Deadline</label>
                            <input id="deadline_at" type="text"
                                   class="form-control @error('deadline_at') is-invalid @enderror"
                                   name="deadline_at" value="{{ old('deadline_at') }}"
                                   placeholder="Vul hier de deadline van de deadine in">
                            @error('deadline_at')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="module_id">Module</label>
                            <select id="module_id" name="module_id"
                                    class="custom-select @error('module_id') is-invalid @enderror">
                                @if(old('module_id') == null)
                                    <option value="" disabled selected hidden>Kies een module voor de deadline</option>
                                @endif
                                @foreach($modules as $module)
                                    @if (old('module_id') == $module->id)
                                        <option value="{{ $module->id }}" selected>{{ $module->name }}</option>
                                    @else
                                        <option value="{{ $module->id }}">{{ $module->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('module_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="difficulty_id">Difficulty</label>
                            <select id="difficulty_id" name="difficulty_id"
                                    class="custom-select @error('difficulty_id') is-invalid @enderror">
                                @if(old('difficulty_id') == null)
                                    <option value="" disabled selected hidden>Kies een difficulty voor de deadline</option>
                                @endif
                                @foreach($difficulty_tags as $difficulty_tag)
                                    @if (old('difficulty_id') == $difficulty_tag->id)
                                        <option value="{{ $difficulty_tag->id }}" selected>{{ $difficulty_tag->name }}</option>
                                    @else
                                        <option value="{{ $difficulty_tag->id }}">{{ $difficulty_tag->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('difficulty_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="time_commitment_id">Time commitment</label>
                            <select id="time_commitment_id" name="time_commitment_id"
                                    class="custom-select @error('time_commitment_id') is-invalid @enderror">
                                @if(old('time_commitment_id') == null)
                                    <option value="" disabled selected hidden>Kies een time commitment voor de deadline</option>
                                @endif
                                @foreach($time_commitment_tags as $time_commitment_tag)
                                    @if (old('time_commitment_id') == $time_commitment_tag->id)
                                        <option value="{{ $time_commitment_tag->id }}" selected>{{ $time_commitment_tag->name }}</option>
                                    @else
                                        <option value="{{ $time_commitment_tag->id }}">{{ $time_commitment_tag->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('time_commitment_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="fun_id">Fun</label>
                            <select id="fun_id" name="fun_id"
                                    class="custom-select @error('fun_id') is-invalid @enderror">
                                @if(old('fun_id') == null)
                                    <option value="" disabled selected hidden>Kies een fun voor de deadline</option>
                                @endif
                                @foreach($fun_tags as $fun_tag)
                                    @if (old('fun_id') == $fun_tag->id)
                                        <option value="{{ $fun_tag->id }}" selected>{{ $fun_tag->name }}</option>
                                    @else
                                        <option value="{{ $fun_tag->id }}">{{ $fun_tag->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('fun_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-12 d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary">Aanmaken van deadline</button>
                            <a href="{{ route('deadlines.index') }}" class="text-secondary align-self-end">Annuleren</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/deadline/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <form action="{{ route('deadlines.update', $deadline->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')

                    <div class="row mb-2">
                        <div class="col-md-12">
                            <h2 class="text-primary">Deadline bewerken</h2>
                            <p>Bewerk een deadline aan om belangrijke momenten in een module bij te houden.</p>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="name" class="text-secondary">Naam / Omschrijving</label>
                            <input id="name" type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name" value="{{ old('name') ?? $deadline->name }}"
                                   placeholder="Vul hier de naam/omschrijving van de deadine in">
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="deadline_at" class="text-secondary">Deadline</label>
                            <input id="deadline_at" type="text"
                                   class="form-control @error('deadline_at') is-invalid @enderror"
                                   name="deadline_at" value="{{ old('deadline_at') ?? $deadline->deadline_at }}"
                                   placeholder="Vul hier de deadline van de deadine in">
                            @error('deadline_at')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="module_id">Module</label>
                            <select id="module_id" name="module_id"
                                    class="custom-select @error('module_id') is-invalid @enderror">
                                @if(old('module_id') ?? $deadline->module_id == null)
                                    <option value="" disabled selected hidden>Kies een module voor de deadline</option>
                                @endif
                                @foreach($modules as $module)
                                    @if (old('module_id') ?? $deadline->module_id == $module->id)
                                        <option value="{{ $module->id }}" selected>{{ $module->name }}</option>
                                    @else
                                        <option value="{{ $module->id }}">{{ $module->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('difficulty_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="difficulty_id">Difficulty</label>
                            <select id="difficulty_id" name="difficulty_id"
                                    class="custom-select @error('difficulty_id') is-invalid @enderror">
                                @if(old('difficulty_id') ?? $deadline->difficulty_id == null)
                                    <option value="" disabled selected hidden>Kies een difficulty voor de deadline</option>
                                @endif
                                @foreach($difficulty_tags as $difficulty_tag)
                                    @if (old('difficulty_id') ?? $deadline->difficulty_id ?? '' == $difficulty_tag->id)
                                        <option value="{{ $difficulty_tag->id }}" selected>{{ $difficulty_tag->name }}</option>
                                    @else
                                        <option value="{{ $difficulty_tag->id }}">{{ $difficulty_tag->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('difficulty_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="time_commitment_id">Time commitment</label>
                            <select id="time_commitment_id" name="time_commitment_id"
                                    class="custom-select @error('time_commitment_id') is-invalid @enderror">
                                @if(old('time_commitment_id') ?? $deadline->time_commitment_id == null)
                                    <option value="" disabled selected hidden>Kies een time commitment voor de deadline</option>
                                @endif
                                @foreach($time_commitment_tags as $time_commitment_tag)
                                    @if (old('time_commitment_id') ?? $deadline->time_commitment_id == $time_commitment_tag->id)
                                        <option value="{{ $time_commitment_tag->id }}" selected>{{ $time_commitment_tag->name }}</option>
                                    @else
                                        <option value="{{ $time_commitment_tag->id }}">{{ $time_commitment_tag->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('time_commitment_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label class="text-secondary" for="fun_id">Fun</label>
                            <select id="fun_id" name="fun_id"
                                    class="custom-select @error('fun_id') is-invalid @enderror">
                                @if(old('fun_id') ?? $deadline->fun_id == null)
                                    <option value="" disabled selected hidden>Kies een fun voor de deadline</option>
                                @endif
                                @foreach($fun_tags as $fun_tag)
                                    @if (old('fun_id') ?? $deadline->fun_id == $fun_tag->id)
                                        <option value="{{ $fun_tag->id }}" selected>{{ $fun_tag->name }}</option>
                                    @else
                                        <option value="{{ $fun_tag->id }}">{{ $fun_tag->name }}</option>
                                    @endif
                                @endforeach
                            </select>
                            @error('fun_id')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-12 d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary">Bewerken van deadline</button>
                            <a href="{{ route('deadlines.index') }}" class="text-secondary align-self-end">Annuleren</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection