routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'SiteController@actionIndex')->name('/');

Auth::routes(['register' => false]);

Route::get('/admin', 'SiteController@actionAdmin')->name('admin');

Route::resource('users', 'UserController');

Route::resource('modules', 'ModuleController');

Route::resource('teachers', 'TeacherController');

Route::resource('deadlines', 'DeadlineController');
Route::get('/deadlines/{deadline}/complete', 'DeadlineController@actionComplete')->name('deadlines.complete');

Route::resource('tags', 'TagController');

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Teacher
 * @package App
 * @property int id
 * @property string name
 * @property string created_at
 * @property string updated_at
 *
 * @property Module[] teacherModules
 * @property Module[] coordinatorModules
 */
class Teacher extends Model
{
    use Encryptable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
    ];

    protected $encryptable = [
        'name',
    ];

    public function teacherModules()
    {
        return $this->hasMany(Module::class, 'teacher_id', 'id');

    }

    public function coordinatorModules()
    {
        return $this->hasMany(Module::class, 'coordinator_id', 'id');
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ModuleStoreUpdateRequest;
use App\Http\Requests\TeacherStoreUpdateRequest;
use App\Teacher;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class TeacherController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return void
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', Teacher::class);
        return view('teacher.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ModuleStoreUpdateRequest $request
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function store(TeacherStoreUpdateRequest $request)
    {
        $this->authorize('create', Teacher::class);
        $data = $request->validated();
        Teacher::create($data);
        return redirect()->route('admin', ['filter' => 'teachers']);
    }

    /**
     * Display the specified resource.
     *
     * @param Teacher $teacher
     * @return void
     */
    public function show(Teacher $teacher)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Teacher $teacher
     * @return Factory|View
     * @throws AuthorizationException
     */
    public function edit(Teacher $teacher)
    {
        $this->authorize('update', $teacher);
        return view('teacher.edit')->with([
            'teacher' => $teacher,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param TeacherStoreUpdateRequest $request
     * @param Teacher $teacher
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(TeacherStoreUpdateRequest $request, Teacher $teacher)
    {
        $this->authorize('update', $teacher);
        $data = $request->validated();
        $teacher->update($data);
        return redirect()->route('admin', ['filter' => 'teachers']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Teacher $teacher
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Teacher $teacher)
    {
        $this->authorize('delete', $teacher);
        Teacher::destroy($teacher->id);
        return redirect()->back();
    }
}

resources/views/teacher/create.blade.php
@extends('layouts.default')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <form action="{{ route('teachers.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('POST')

                    <div class="row mb-2">
                        <div class="col-md-12">
                            <h2 class="text-primary">Teacher aanmaken</h2>
                            <p>Maak een teacher aan om deze bij een module te kopppelen.</p>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="name" class="text-secondary">Teacher naam</label>
                            <input id="name" type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name" value="{{ old('name') }}"
                                   placeholder="Vul hier de naam van de teacher in">
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-12 d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary">Aanmaken van teacher</button>
                            <a href="{{ route('admin') }}" class="text-secondary align-self-end">Annuleren</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/teacher/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <form action="{{ route('teachers.update', $teacher->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')

                    <div class="row mb-2">
                        <div class="col-md-12">
                            <h2 class="text-primary">Teacher bewerken</h2>
                            <p>Bewerk een teacher aan om deze bij een module te kopppelen.</p>
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-12">
                            <label for="name" class="text-secondary">Teacher naam</label>
                            <input id="name" type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name" value="{{ old('name') ?? $teacher->name }}"
                                   placeholder="Vul hier de naam van de module in">
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-12 d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary">Bewerken van teacher</button>
                            <a href="{{ route('admin') }}" class="text-secondary align-self-end">Annuleren</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection