routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'SiteController@actionIndex')->name('/');

Auth::routes(['register' => false]);

Route::get('/admin', 'SiteController@actionAdmin')->name('admin');

Route::resource('users', 'UserController');

Route::resource('modules', 'ModuleController');

Route::resource('teachers', 'TeacherController');

Route::resource('deadlines', 'DeadlineController');
Route::get('/deadlines/{deadline}/complete', 'DeadlineController@actionComplete')->name('deadlines.complete');

Route::resource('tags', 'TagController');

app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use App\Module;
use App\Teacher;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\View\View;

class SiteController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except(['actionIndex']);
    }

    /**
     * @return Factory|View
     */
    public function actionIndex()
    {

        return view('site.index')->with([
            'module_ids' => Module::getModuleIds(),
            'semester_ids' => Module::getSemesterIds(),
            'modules' => Module::all(),
            'total_semesters' => count(Module::getSemesterIds())
        ]);
    }

    public function actionAdmin(Request $request)
    {
        if (auth()->user()->type != 'admin') return redirect()->back();
        $search = $request->search ?? '';
        $filter = $request->filter ?? 'modules';
        if ($filter === 'modules') {
            $data = Module::where('name', 'lIKE', '%' . $search . '%')->orderBy('updated_at', 'desc')->paginate();
        } elseif ($filter === 'teachers') {
            $data = Teacher::orderBy('updated_at', 'desc')->paginate();
        } else {
            return redirect()->back();
        }
        return view('site.admin')->with([
            'data' => $data->items(),
            'search' => $search,
            'filter' => $filter,
            'totalCount' => $data->total(),
            'currentPage' => $data->currentPage(),
            'lastPage' => $data->lastPage(),
        ]);
    }
}

resources/views/site/admin.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="vacancy-list-header col-md-12 d-flex justify-content-center align-items-center">
                <form action="{{ route('admin') }}" method="GET">
                    <div class="search-form d-flex flex-row">
                        @if($filter === 'modules')
                            <a class="search-create search-form-shadow-group d-flex align-items-center justify-content-center"
                               href="{{ route('modules.create') }}">
                                <i class="fas fa-plus text-white create"></i>
                            </a>
                            <div class="search-form-shadow-group ml-2 d-flex flex-row">
                                <input class="form-control w-100" id="search" name="search"
                                       placeholder="Zoeken naar module(s)"
                                       type="text" value="{{ $search }}">
                                <input type="hidden" name="filter" value="{{ $filter }}">
                                <input type="hidden" name="page" value="{{ $currentPage }}">
                                <button class="search-submit d-flex align-items-center justify-content-center"
                                        type="submit">
                                    <i class="fas fa-search text-white"></i>
                                </button>
                            </div>
                        @elseif($filter === 'teachers')
                            <a class="search-create search-form-shadow-group d-flex align-items-center justify-content-center"
                               href="{{ route('teachers.create') }}">
                                <i class="fas fa-plus text-white create"></i>
                            </a>
                            <div class="search-form-shadow-group ml-2 d-flex flex-row">
                                <input class="form-control w-100" id="search" name="search"
                                       placeholder="Zoeken naar teacher(s)"
                                       type="text" value="{{ $search }}">
                                <input type="hidden" name="filter" value="{{ $filter }}">
                                <input type="hidden" name="page" value="{{ $currentPage }}">
                                <button class="search-submit d-flex align-items-center justify-content-center"
                                        type="submit">
                                    <i class="fas fa-search text-white"></i>
                                </button>
                            </div>
                        @endif
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="vacancy-list-filter col-md-12 d-flex justify-content-center align-items-center">
                <a class="btn btn-link @if($filter === 'modules') btn-link-active @endif text-white mx-2"
                   href="{{ route('admin', ['filter' => 'modules', 'search' => $search, 'page' => $currentPage]) }}">Modules</a>
                <a class="btn btn-link @if($filter === 'teachers') btn-link-active @endif text-white mx-2"
                   href="{{ route('admin', ['filter' => 'teachers', 'search' => $search, 'page' => $currentPage]) }}">Teachers</a>
            </div>
        </div>
        @if($lastPage > 1)
            <div class="row fixed-bottom mb-4">
                <div class="col-md-12 d-flex flex-row justify-content-center align-items-center">
                    @for($i = 1; $i <= $lastPage; $i++)
                        <a class="pagination-item @if($currentPage == $i) pagination-item-active @endif d-flex align-items-center justify-content-center text-white mx-1"
                           href="{{ route('admin', ['filter' => $filter, 'search' => $search, 'page' => $i]) }}">
                            <label class="mb-0">{{ $i }}</label>
                        </a>
                    @endfor
                </div>
            </div>
        @endif
        <div class="row">
            <div class="col-md-12 p-0">
                <ul class="vacancy-list p-0 m-0">
                    <li class="hover">
                        <div class="row no-gutters">
                            <div class="col-md-12">
                                <div class="vacancy-count d-flex flex-row">
                                    <small>{{ $totalCount }} resultaten</small>
                                </div>
                            </div>
                        </div>
                    </li>
                    <?php
                    use App\Module;use App\Teacher;$i = 1;
                    for ($x = 1; $x < $currentPage; $x++) {
                        $i += 15;
                    }
                    ?>
                    @foreach($data as $item)
                        <li class="hover">
                            <div class="row no-gutters">
                                <div class="col-md-12">
                                    <div class="vacancy d-flex justify-content-between flex-row">
                                        <div class="d-flex flex-row">
                                            <small>{{ $i }}</small>
                                            @if($filter === 'modules')
                                                <?php /** @var Module $item */ ?>
                                                <h5 class="pl-2">{{ $item->name }}</h5>
                                                <p class="m-0 pl-2">Period: {{ $item->period }}</p>
                                                <p class="m-0 pl-2">EC: {{ $item->ec }}</p>
                                                <p class="m-0 pl-2">Completed: {{ $item->completed ? 'ja' : 'nee' }}</p>
                                                <p class="m-0 pl-2">Score: {{ $item->score ?? 'NA' }}</p>
                                                <p class="m-0 pl-2">Type: {{ $item->type }}</p>
                                                <p class="m-0 pl-2">Teacher: {{ $item->teacher->name ?? '' }}</p>
                                                <p class="m-0 pl-2">Coordinator: {{ $item->coordinator->name ?? '' }}</p>
                                                    @if($item->file_path != null) <p class="m-0 pl-2"><a href="/storage/{{$item->file_path}}">File download</a></p> @endif
                                            @elseif($filter === 'teachers')
                                                <?php /** @var Teacher $item */ ?>
                                                <h5 class="pl-2">{{ $item->name }}</h5>
                                            @endif
                                        </div>
                                        <div class="d-flex flex-row">
                                            <p class="m-0 pl-2">{{ $item->updated_at }}</p>
                                            <div class="dropdown ml-2">
                                                <button type="button" class="btn btn-primary dropdown-toggle"
                                                        data-toggle="dropdown" aria-expanded="false">
                                                    <i class="fas fa-angle-up"></i>
                                                </button>
                                                <ul class="text-left dropdown-menu p-0">
                                                    @if($filter === 'modules')
                                                        <?php /** @var Module $item */ ?>
                                                        <a href="{{ route('modules.edit', $item->id) }}">Bewerken</a>
                                                        <a href="{{ route('modules.destroy', $item->id) }}"
                                                           onclick="event.preventDefault();
                                                               document.getElementById('delete-form-{{$item->id}}').submit();">Verwijderen</a>
                                                        <form id="delete-form-{{$item->id}}"
                                                              action="{{ route('modules.destroy', $item->id) }}"
                                                              method="POST">
                                                            @method('DELETE')
                                                            @csrf
                                                        </form>
                                                    @elseif($filter === 'teachers')
                                                        <?php /** @var Teacher $item */ ?>
                                                        <a href="{{ route('teachers.edit', $item->id) }}">Bewerken</a>
                                                        <a href="{{ route('teachers.destroy', $item->id) }}"
                                                           onclick="event.preventDefault();
                                                               document.getElementById('delete-form-{{$item->id}}').submit();">Verwijderen</a>
                                                        <form id="delete-form-{{$item->id}}"
                                                              action="{{ route('teachers.destroy', $item->id) }}"
                                                              method="POST">
                                                            @method('DELETE')
                                                            @csrf
                                                        </form>
                                                    @endif
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <?php $i++ ?>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endsection

resources/views/site/index.blade.php
@extends('layouts.default')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="m-2 mb-4">Progressie page</h1>
                <div class="card">
                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <nav>
                            <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                                @foreach($semester_ids as $semester_id)
                                    <a class="nav-item nav-link act {{$semester_id ===  1 ? 'active' : ''}}"
                                       id="nav-tab-{{$semester_id}}"
                                       data-toggle="tab" href="#nav-profile-{{$semester_id}}" role="tab"
                                       aria-controls="nav-profile-{{$semester_id}}"
                                       aria-selected="false">Semester {{$semester_id}}
                                    </a>
                                @endforeach
                                @foreach($module_ids as $module_id)
                                    <a class="nav-item nav-link act" id="nav-tab-{{$module_id + $total_semesters}}"
                                       data-toggle="tab" href="#nav-profile-{{$module_id + $total_semesters}}"
                                       role="tab"
                                       aria-controls="nav-profile-{{$module_id + $total_semesters}}"
                                       aria-selected="false">Blok {{$module_id}}
                                    </a>
                                @endforeach
                            </div>
                        </nav>
                        <div class="tab-content" id="nav-tabContent">
                            @foreach($semester_ids as $semester_id)
                                <div class="tab-pane fade show" id="nav-profile-{{$semester_id}}"
                                     aria-labelledby="nav-tab-{{$semester_id}}">
                                    <table class="table" cellspacing="0">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Recieved / Total EC</th>
                                            <th>Grade</th>
                                        </tr>
                                        </thead>
                                        @php
                                            $amount_of_subjects = 0;
                                            $amount_of_completed_subjects = 0
                                        @endphp
                                        @foreach($modules as $module)
                                            @if(ceil(($module->period / 2)) == $semester_id)
                                                @php
                                                    $amount_of_subjects++
                                                @endphp
                                                <tbody>
                                                <tr>
                                                    <td>{{$module->name}}</td>

                                                    @if($module->completed)
                                                        @php
                                                            $amount_of_completed_subjects++
                                                        @endphp
                                                        <td>{{$module->ec}}/{{$module->ec}}</td>
                                                    @else
                                                        <td>0/{{$module->ec}}</td>
                                                    @endif

                                                    @if($module->score == null)
                                                        <td>Not graded</td>
                                                    @else
                                                        <td>{{$module->score}}</td>
                                                    @endif
                                                </tr>
                                                </tbody>
                                            @endif
                                        @endforeach
                                    </table>
                                    <div class="progress">
                                        @if($amount_of_completed_subjects === 0 )
                                            <div class="progress-bar progress-bar-striped" role="progressbar"
                                                 style="width: 3%;" aria-valuenow="0" aria-valuemin="0"
                                                 aria-valuemax="100">
                                                0%
                                            </div>
                                        @else
                                            <div class="progress-bar progress-bar-striped" role="progressbar"
                                                 style="width: {{ceil($amount_of_completed_subjects / $amount_of_subjects * 100)}}%;"
                                                 aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                                                {{ceil($amount_of_completed_subjects / $amount_of_subjects * 100)}}%
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            @endforeach
                            @foreach($module_ids as $module_id)
                                <div class="tab-pane fade show" id="nav-profile-{{$module_id + $total_semesters}}"
                                     aria-labelledby="nav-tab-{{$module_id + $total_semesters}}">
                                    <table class="table" cellspacing="0">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Recieved / Total EC</th>
                                            <th>Grade</th>
                                        </tr>
                                        </thead>
                                        @php
                                            $amount_of_subjects = 0;
                                            $amount_of_completed_subjects = 0
                                        @endphp
                                        @foreach($modules as $module)
                                            @if($module->period === $module_id)
                                                @php
                                                    $amount_of_subjects++
                                                @endphp
                                                <tbody>
                                                <tr>
                                                    <td>{{$module->name}}</td>
                                                    @if($module->completed)
                                                        @php
                                                            $amount_of_completed_subjects++
                                                        @endphp
                                                        <td>{{ $module->ec }}/{{ $module->ec }}</td>
                                                    @else
                                                        <td>0/{{$module->ec}}</td>
                                                    @endif

                                                    @if($module->score == null)
                                                        <td>Not graded</td>
                                                    @else
                                                        <td>{{$module->score}}</td>
                                                    @endif
                                                </tr>
                                                </tbody>
                                            @endif
                                        @endforeach
                                    </table>
                                    <div class="progress">
                                        @if($amount_of_completed_subjects === 0 )
                                            <div class="progress-bar progress-bar-striped" role="progressbar"
                                                 style="width: 3%;" aria-valuenow="0" aria-valuemin="0"
                                                 aria-valuemax="100">
                                                0%
                                            </div>
                                        @else
                                            <div class="progress-bar progress-bar-striped" role="progressbar"
                                                 style="width: {{ceil($amount_of_completed_subjects / $amount_of_subjects * 100)}}%;"
                                                 aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
                                                {{ceil($amount_of_completed_subjects / $amount_of_subjects * 100)}}%
                                            </div>
                                        @endif
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection